# FlowSQL Config

# You can define the default password in config.php.
# Defaults: false, "root", true
autologin: false
default_login_user: "root"
require_ip: true

# Updates: **work in progress**
# When update is set to true, it will frequently check for updates and ask you to update
# update_src defines where updates are sourced. It must be a JSON output with a "zipball_url" key. 
# latest_config defines where the latest version of the default config file is stored.
# Defaults: false, https://api.github.com/repos/ethrythedev/FlowSQL/releases/latest, https://cdn.jsdelivr.net/gh/ethrythedev/FlowSQL@latest/config.yml
update: false
update_src: "https://api.github.com/repos/ethrythedev/FlowSQL/releases/latest"
latest_config: "https://cdn.jsdelivr.net/gh/ethrythedev/FlowSQL@latest/config.yml"

# Privacy:
# Options: "bunny", "google", "none"
# Default: "bunny"
font_src: "bunny"

# Server location:
# Defaults: localhost, 3306, false
server_location: "localhost"
server_port: 3306
allow_ext_srcs: false

# Errors: **work in progress**
# These may be helpful for debugging.
# Default: true
allow_php_default_errors: true

# Please do not change the values below
config_version: 1.0.0